defaults: &defaults
    macos:
        xcode: 12.4.0

version: 2.1

jobs:
    Build and Test:
        <<: *defaults
        steps:
        - checkout
        - run:
            name: Build Tests
            command: swift build --build-tests --disable-automatic-resolution -v
        - run:
            name: Run Tests
            command: swift test --disable-automatic-resolution -v

workflows:
    version: 2

    Build and Test:
        jobs:
            - Build and Test
